packages:
  patchelf:
    buildable: false
    paths: {patchelf: /cvmfs/sw-nightlies.hsf.org/key4hep/nightlies/LCG_96c_LS/linux-centos7-haswell/gcc-4.8.5/patchelf-0.10-uuw7pepqm55i6qo6apsxt2eoyul5kjf2}
